// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0ab35cf8-be54-402f-aa46-11e5eed44ddc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zVoBYFc9C",
    "aws_user_pools_web_client_id": "3cqe13itm1ilcbouhp9vjitsgv",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "txs-comp",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
